### ISSUE TITLE
Go to forked URL after fork

### ISSUE THREAD

**Issue by pfrazee** [kodedninja/ridder#2]
Hey @kodedninja! I love Ridder and I want to feature it on the new explore page. There's one tweak that I think it needs --

Right now, when you fork, Ridder doesn't navigate to the fork. It just stays on the page (nothing happens). Could you update it so that Ridder redirects to the fork's URL after the fork is done?

(I'd PR the change myself but the source here seems different than what's published.)

**Comment by kodedninja** [comment]
Hey, you're talking about dat://ridder-kodedninja.hashbase.io/, right? The source is Ridder (the app) itself and this is a separate site just for the landing page part.

I'll update it, for sure! But also worth mentioning, that I didn't really focus much on Ridder. I'm sure it has a lot of bugs and features to do haha

**Comment by pfrazee** [comment]
Oh that explains it! 😅 

No worries about the focus. Ridder looks great and it demos some key behavior. That's all I'm looking for right now.

**Comment by kodedninja** [comment]
Glad to hear! :smile:
