### ISSUE TITLE
Wrong date displayed for November.

### ISSUE THREAD

**Issue by SirRujak** [kodedninja/ridder#5]
I added the FiveThirtyEight rss feed to my ridder instance and it is displaying November entries as being in December of this year. The rss feed appears to be correct so I'm not quite sure where the issue is occuring.

Here is a link to their feed in case that helps:

https://fivethirtyeight.com/all/feed

**Comment by kodedninja** [comment]
Haha, thanks. Yeah, for some reason November was missing from a months array. It's fixed now.

**Comment by SirRujak** [comment]
Thanks! I appreciate it!
